export const SEARCH_VALUE_CHANGE = 'SEARCH_VALUE_CHANGE';
export const NODE_TITLE_SUCCEEDED = 'NODE_TITLE_SUCCEEDED';
export const NODE_TITLE_FAILED = 'NODE_TITLE_FAILED';
export const NODE_TITLE_CLEAR = 'NODE_TITLE_CLEAR';
